name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r backend/requirements.txt
          pip install -r frontend/requirements.txt

      - name: Run Tests
        run: |
          python -m unittest discover -s backend/tests || echo "No tests found."

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build Docker Image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/llmops-pipeline

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy llmops-pipeline \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/llmops-pipeline \
            --platform managed \
            --region europe-west8 \
            --allow-unauthenticated
